<?php

return [
    'fa-star'        => 'Star',
    'fa-bullseye'    => 'Bullseye',
    'fa-line-chart'  => 'Line Chart',
    'fa-bar-chart'   => 'Bar Chart',
    'fa-pie-chart'   => 'Pie Chart',
    'fa-rocket'      => 'Rocket',
    'fa-lightbulb-o' => 'Lightbulb',
    'fa-cogs'        => 'Cogs',
    'fa-cog'         => 'Gear',
    'fa-database'    => 'Database',
    'fa-cloud'       => 'Cloud',
    'fa-shield'      => 'Shield',
    'fa-lock'        => 'Lock',
    'fa-users'       => 'Users',
    'fa-user-circle-o' => 'User Circle',
    'fa-check-square-o' => 'Check Square',
    'fa-check-circle-o' => 'Check Circle',
    'fa-download'    => 'Download',
    'fa-file-pdf-o'  => 'File PDF',
    'fa-book'        => 'Book',
    'fa-graduation-cap' => 'Graduation Cap',
    'fa-mobile'      => 'Mobile',
    'fa-laptop'      => 'Laptop',
    'fa-desktop'     => 'Desktop',
    'fa-money'       => 'Money',
    'fa-handshake-o' => 'Handshake',
    'fa-thumbs-up'   => 'Thumbs Up',
    'fa-heart'       => 'Heart',
    'fa-trophy'      => 'Trophy',
    'fa-gift'        => 'Gift',
    'fa-search'      => 'Search',
    'fa-envelope-o'  => 'Envelope',
    'fa-phone'       => 'Phone',
    'fa-globe'       => 'Globe',
    'fa-wifi'        => 'Wifi',
    'fa-briefcase'   => 'Briefcase',
    'fa-comments'    => 'Comments',
    'fa-calculator'  => 'Calculator',
    'fa-credit-card' => 'Credit Card',
    'fa-shopping-cart' => 'Cart',
    'fa-truck'       => 'Truck',
    'fa-industry'    => 'Industry',
    'fa-building-o'  => 'Building',
];
